//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTasks
    {
        public int EtId { get; set; }
        public string EtTitle { get; set; }
        public int EtStatus { get; set; }
        public int EtPriority { get; set; }
        public int EtAuthor { get; set; }
        public int EtExecutor { get; set; }
        public System.DateTime EtEstimate { get; set; }
        public string EtDescription { get; set; }
    }
}
